wildcat/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'


urlpatterns = [
    path('login', views.LoginPage.as_view(), name='login'),
    path('register', views.RegisterPage.as_view(), name='register'),
    path('logout', views.LogOutPage.as_view(), name='logout'),
    path('@<slug:slug>', views.AccountPage.as_view(), name='account_page'),
    path('settings', views.AccountSettingsPage.as_view(), name='settings'),
    path('settings/delete-account', views.AccountDelete.as_view(), name='delete_account'),
]

wildcat/api/urls.py
from django.urls import path
from api.views import ProductListView, AddStarApiView, FollowUserApiView, ChangeCommentlikeApiView, ChangeCommentDislikeApiView, DeleteComment, GetNotifications

app_name = 'api'

urlpatterns = [
    path('products', ProductListView.as_view(), name='products_api'),
    path('products/star/<int:pk>', AddStarApiView.as_view(), name='product_star'),
    path('products/comments/like/<int:pk>', ChangeCommentlikeApiView.as_view(), name='like_comment'),
    path('products/comments/dislike/<int:pk>', ChangeCommentDislikeApiView.as_view(), name='dislike_comment'),
    path('products/comments/delete/<int:pk>', DeleteComment.as_view(), name='delete_comment'),
    path('accounts/follow/<int:pk>', FollowUserApiView.as_view(), name='account_follow'),
    path('notifications', GetNotifications.as_view(), name='notifications')
]

wildcat/products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.IndexPage.as_view(), name='index'),
    path('add-product', views.ProductAdditionPage.as_view(), name='product_addition'),
    path('@<slug:user_slug>/<slug:product_slug>', views.ProductPage.as_view(), name='product'),
    path('@<slug:user_slug>/<slug:product_slug>/edit', views.EditProductPage.as_view(), name='edit_product'),
    path('@<slug:user_slug>/<slug:product_slug>/delete', views.DeleteProduct.as_view(), name='delete_product'),
    path('404', views.tera_test, name='404'),    
]

wildcat/templates/users/profile.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load humanize %}
{% block title %}Wildcat | {{ account.username }}{% endblock %}
{% block content %}
    <div x-data="tabHandler()" class="w-4/5 sm:w-11/12 md:w-11/12 mx-auto flex flex-col gap-7 p-7 sm:p-4 mb-10 bg-con-l dark:bg-con-d rounded-lg">
        <!-- Profile -->
        <div class="flex flex-row">
            <div class="flex flex-row w-5/6 gap-7 sm:gap-3">
                <div>
                    <img src="{{ account.image.url }}"
                   alt="user"
                   class="rounded-full w-full h-48 md:h-32 md:w-32 sm:h-20 sm:w-20 flex justify-start">
                </div>
                <div class="flex flex-col px-2 py-4 gap-4">
                    <div class="flex flex-row gap-4 items-center">
                        <h2 class="text-4xl md:text-3xl sm:text-2xl font-bold">{{ account.username }}</h2>
                    </div>
                    <div class="flex flex-row gap-10 sm:hidden">
                        <div>
                            <p class="text-slate-500 dark:text-gray-400">
                                Products: <span class="font-bold text-black dark:text-white">{{ products.count }}</span>
                            </p>
                        </div>
                        <div>
                            <p class="text-slate-500 dark:text-gray-400">
                                Followers: <span class="font-bold text-black dark:text-white">{{ account.follows.count }}</span>
                            </p>
                        </div>
                    </div>
                    <div class="flex flex-col sm:hidden">
                        <p class="text-slate-500 dark:text-slate-300/60">About:</p>
                        <p class="text-justify">
                            {{ account.bio }}
                        </p>
                    </div>
                </div>
            </div>
            <!--mobile-->
            
            <!-- Buttons -->
            <div class="w-1/6 flex flex-col items-end gap-2">
                {% if user == account %}
                <a href="{% url 'accounts:settings' %}" class="w-10 h-10 hover:text-green-hov hover:scale-110 duration-200 transition-all">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-full h-full">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.56.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.893.149c-.425.07-.765.383-.93.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.397.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.273-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.107-1.204l-.527-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894z" />
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                </a>
                {% else %}
                <button x-data="followHandler({% if user in account.follows.all %}true{% else %}false{% endif %},{{ account.follows.count }},{{ account.pk }})" x-html="currentSvg" @click="changeFollow()" class="w-10 h-10 hover:text-green-hov hover:scale-110 duration-200 transition-all">
                {% endif %}
            </div>
        </div>
        <div class="hidden w-full sm:flex flex-col gap-3">
            <div class="flex flex-row gap-10">
                <div>
                    <p class="text-slate-500 dark:text-gray-400">
                        Products: <span class="font-bold text-black dark:text-white">{{ products.count }}</span>
                    </p>
                </div>
                <div>
                    <p class="text-slate-500 dark:text-gray-400">
                        Followers: <span class="font-bold text-black dark:text-white">{{ account.follows.count }}</span>
                    </p>
                </div>
                <div>
                    <p class="text-slate-500 dark:text-gray-400">
                        Following: <span class="font-bold text-black dark:text-white">{{ account_following }}</span>
                    </p>
                </div>
            </div>
            <p class="text-slate-500 dark:text-slate-300/60">About:</p>
            {{ account.bio }}
        </div>
        <!-- tabs changer -->
        <div class="flex justify-start border-b border-slate-900/10 dark:border-slate-300/10">
            <div class="grid grid-cols-2">
                <button @click="changeTab('itemsTab')" :class="openTab['itemsTab'] && 'text-green-l dark:text-green-d font-bold border-b-4 border-[#6aa93b] dark:border-[#649d39]'" class="flex justify-center cursor-pointer hover:bg-[#c6c6c6] dark:hover:bg-[#595959] px-2 transition-all duration-100 ease-in-out rounded-t-sm">
                    <p>Items</p>
                </button>
                <button @click="changeTab('favoriteTab')" :class="openTab['favoriteTab'] && 'text-green-l dark:text-green-d font-bold border-b-4 border-[#6aa93b] dark:border-[#649d39]'" class="flex justify-center cursor-pointer hover:bg-[#c6c6c6] dark:hover:bg-[#595959] px-2 transition-all duration-100 ease-in-out rounded-t-sm">
                    <p>Favourite</p>
                </button>
            </div>
        </div>
        <!-- Owned products -->
        <div x-show="openTab['itemsTab']" class="grid grid-cols-4 sm:grid-cols-1 md:grid-cols-2 gap-5">
            {% for product in products %}
                <div class="h-80 flex flex-col overflow-hidden">
                    <a href="{% url 'products:product' account.slug product.slug %}"
                       class="shadow-md rounded-lg bg-blend-normal h-3/4">
                        <img src="{{ product.main_image.url }}"
                             alt="image"
                             class="w-full h-full object-cover rounded-lg object-center">
                    </a>
                    <div class="flex flex-row justify-between items-center">
                        <a href="{% url 'products:product' account.slug product.slug %}"
                           class="text-lg font-semibold hover:text-green-hov">{{ product.name }}</a>
                        <p class="flex-none">{{ product.price }} zł</p>
                    </div>
                    <div class="flex flex-row justify-between items-center">
                        <p class="text-gray-700 dark:text-gray-400">{{ product.date|naturalday }}</p>
                        <div class="flex justify-center">
                            <div class="flex justify-center"
                                 x-data="starHandler({% if user in product.stars.all %}true{% else %}false{% endif %},{{ product.stars__count }},{{ product.pk }})">
                                <button x-html="currentSvg"
                                        @click="changeStar()"
                                        class="hover:scale-110 transition-all duration-200 w-6 h-6"
                                        {% if not user.is_authenticated or user == product.owner %}disabled{% endif %}>
                                </button>
                                <p x-text="count" class="ml-1 text-gray-400"></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <!-- Favourite products -->
        <div x-show="openTab['favoriteTab']" class="grid grid-cols-4 sm:grid-cols-1 md:grid-cols-2 gap-5">
            {% for product in favorite %}
                <div class="h-80 flex flex-col overflow-hidden">
                    <a href="{% url 'products:product' account.slug product.slug %}"
                       class="shadow-md rounded-lg bg-blend-normal h-3/4">
                        <img src="{{ product.main_image.url }}"
                             alt="image"
                             class="w-full h-full object-cover rounded-lg object-center">
                    </a>
                    <div class="flex flex-row justify-between items-center">
                        <a href="{% url 'products:product' account.slug product.slug %}"
                           class="text-lg font-semibold hover:text-green-hov">{{ product.name }}</a>
                        <p class="flex-none">{{ product.price }} zł</p>
                    </div>
                    <div class="flex flex-row justify-between items-center">
                        <p class="text-gray-700 dark:text-gray-400">{{ product.date|naturalday }}</p>
                        <div class="flex justify-center">
                            <div class="flex justify-center"
                                 x-data="starHandler({% if user in product.stars.all %}true{% else %}false{% endif %},{{ product.stars__count }},{{ product.pk }})">
                                <button x-html="currentSvg"
                                        @click="changeStar()"
                                        class="hover:scale-110 transition-all duration-200 w-6 h-6"
                                        {% if not user.is_authenticated or user == product.owner %}disabled{% endif %}>
                                </button>
                                <p x-text="count" class="ml-1 text-gray-400"></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/apiHandler.js' %}"></script>
    <script>
        function tabHandler() {
            return {
                openTab: {
                    itemsTab: true, 
                    favoriteTab: false
                }, 
                changeTab(setting) {
                    for (let [key, value] of Object.entries(this.openTab)) {
                        this.openTab[key] = false
                    }
                    this.openTab[setting] = true
                }
            }
        }
    </script>
{% endblock scripts %}

wildcat/templates/users/settings.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}Wildcat | Settings{% endblock %}
{% block content %}
    <div x-data="settings()"
         class="w-4/5 sm:w-11/12 mx-auto flex flex-col gap-8 p-7 sm:p-4 mb-10 bg-con-l dark:bg-con-d rounded-lg">
        <div class="grid grid-cols-10">
            <div class="col-span-3">
                <h1 class="text-2xl mb-5">Settings</h1>
                <ul>
                    <li>
                        <button @click="changeSettings('profileDetailsOpen')" :class="openSettings['profileDetailsOpen'] && 'font-bold text-green-l dark:text-green-d'" class="hover:text-green-l hover:dark:text-green-d transition-all duration-150">Profile detail</button>
                    </li>
                    <li>
                        <button @click="changeSettings('accountSettingsOpen')" :class="openSettings['accountSettingsOpen'] && 'font-bold text-green-l dark:text-green-d'" class="hover:text-green-l hover:dark:text-green-d transition-all duration-150">Account settings</button>
                    </li>
                </ul>
            </div>
            <div class="col-span-7">
                <!-- Profile detail -->
                <form action="" method="post" enctype="multipart/form-data" x-show="openSettings['profileDetailsOpen']" x-cloak class="block">
                    {% csrf_token %}
                    <div class="grid grid-rows-1 gap-5">
                        <div class="border border-slate-900/10 dark:border-slate-300/10 rounded-lg px-3 sm:text-sm">
                            <div class="grid grid-cols-2 sm:grid-cols-1 h-24">
                                <div class="my-auto">
                                    <p class="text-lg sm:text-sm">Your photo</p>
                                </div>
                                <div class="flex justify-end sm:justify-center my-auto sm:ml-6 sm:text-xs">
                                    <img src="{{ user.image.url }}"
                                         alt="user"
                                         class="rounded-full h-16 sm:h-8 md:h-10">
                                    <div class="my-auto ml-2">
                                        {% render_field form.image class="text-sm md:text-xs sm:text-xs text-black dark:text-white file:mr-3 sm:file:mr-1 file:py-1 sm:file:py-0 file:px-2 sm:file:px-1 file:rounded-full file:border-solid dark:file:border-green-d file:text-sm sm:file:text-xs file:text-green-l hover:file:text-green-hov file:bg-con-l dark:file:bg-con-d hover:file:border-green-hov dark:hover:file:border-green-hov focus:outline-none" %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="border border-slate-900/10 dark:border-slate-300/10 rounded-lg px-3 sm:text-sm">
                            <div class="grid grid-cols-2 h-auto">
                                <p class="my-auto text-lg sm:text-sm">About You</p>
                                <div class="flex justify-end my-auto py-3">
                                    {% render_field form.bio class="bg-con-l dark:bg-con-d border sm:text-xs border-slate-900/10 dark:border-slate-300/10 focus:bg-form-l focus:dark:bg-form-d rounded-xl focus:ring-green-hov resize-none" rows="5" cols="35" placeholder="Tell more about yourself..." %}
                                </div>
                            </div>
                        </div>
                        <div class="border border-slate-900/10 dark:border-slate-300/10 rounded-lg px-3 sm:text-sm">
                            <div class="grid grid-cols-2 h-auto">
                                <p class="my-auto text-lg sm:text-sm">
                                    Country
                                </p>
                                <div class="flex justify-end my-auto py-3">
                                    {% render_field form.country class="w-4/5 bg-con-l dark:bg-con-d border border-slate-900/10 dark:border-slate-300/10 focus:bg-form-l focus:dark:bg-form-d rounded-xl focus:ring-green-hov" placeholder="USA" %}
                                </div>
                            </div>
                        </div>
                        <div class="border border-slate-900/10 dark:border-slate-300/10 rounded-lg px-3 sm:text-sm">
                            <div class="grid grid-cols-2 h-auto">
                                <p class="my-auto text-lg sm:text-sm">
                                    Town/City
                                </p>
                                <div class="flex justify-end my-auto py-3">
                                    {% render_field form.city class="w-4/5 bg-con-l dark:bg-con-d border border-slate-900/10 dark:border-slate-300/10 focus:bg-form-l focus:dark:bg-form-d rounded-xl focus:ring-green-hov" placeholder="City of New York" %}
                                </div>
                            </div>
                        </div>
                        <div class="border border-slate-900/10 dark:border-slate-300/10 rounded-lg px-3">
                            <div class="grid grid-cols-2 h-auto">
                                <p class="my-auto text-lg sm:text-sm">Language</p>
                                <div class="flex justify-end my-auto py-3">
                                    <select name=""
                                            id=""
                                            class="bg-form-l dark:bg-form-d border border-slate-900/10 dark:border-slate-300/10 rounded-2xl w-1/2 sm:w-4/5 md:w-4/5">
                                        <option value="EN">
                                            English (Angielski)
                                        </option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="flex justify-end mx-2">
                            <button type="submit" class="text-white bg-green-l dark:bg-green-d hover:bg-green-hov rounded-xl px-3 py-2">Update profile</button>
                        </div>
                    </div>
                </form>
                <!-- Account settings -->
                <div x-show="openSettings['accountSettingsOpen']" x-cloak>
                    <div class="grid grid-rows-1 gap-5">
                        <div class="border border-slate-900/10 dark:border-slate-300/10 rounded-lg px-3 sm:text-sm">
                            <div class="grid grid-cols-2 h-20">
                                <div class="my-auto">
                                    <p class="text-lg sm:text-sm">Your e-mail</p>
                                </div>
                                <div class="flex justify-end my-auto mr-4 sm:mr-2">{{ user.email }}</div>
                            </div>
                        </div>
                        <div class="border border-slate-900/10 dark:border-slate-300/10 rounded-lg px-3 sm:text-sm">
                            <div class="grid grid-cols-2 h-20">
                                <div class="my-auto">
                                    <p class="my-auto text-lg sm:text-sm">Your username</p>
                                </div>
                                <div class="flex justify-end my-auto mr-4 sm:mr-2">{{ user.username }}</div>
                            </div>
                        </div>
                        <div class="border border-slate-900/10 dark:border-slate-300/10 rounded-lg px-3 sm:text-sm">
                            <div class="grid grid-cols-2 h-20">
                                <div class="my-auto">
                                    <p class="my-auto text-lg sm:text-sm">Change password</p>
                                </div>
                                <div class="flex justify-end my-auto">
                                    <button class="mr-3 py-1 px-2 rounded-full border border-green-l dark:border-green-d text-green-l hover:text-green-hov bg-con-l dark:bg-con-d hover:border-green-hov dark:hover:border-green-hov">
                                        Change
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="border border-slate-900/10 dark:border-slate-300/10 rounded-lg px-3 sm:text-sm">
                            <div class="grid grid-cols-2 h-20">
                                <div class="my-auto">
                                    <p class="text-lg sm:text-sm">Delete account</p>
                                </div>
                                <div class="flex justify-end my-auto">
                                    <a href="{% url 'accounts:delete_account' %}" class="mr-3 py-1 px-2 rounded-full border border-red-600 text-red-600 hover:text-red-700 bg-con-l dark:bg-con-d hover:border-red-700">
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>
        function settings() {
            return {
                openSettings: {
                    profileDetailsOpen: true, 
                    accountSettingsOpen: false
                }, 
                changeSettings(setting) {
                    for (let [key, value] of Object.entries(this.openSettings)) {
                        this.openSettings[key] = false
                    }
                    this.openSettings[setting] = true
                }
            }
        }
    </script>
{% endblock scripts %}

wildcat/templates/users/user_profile.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load humanize %}
{% block title %}Wildcat | Product addition{% endblock %}
{% block content %}
    <div class="w-4/5 sm:w-11/12 mx-auto flex flex-col gap-7 p-7 sm:p-0 mb-10 bg-con-l dark:bg-con-d rounded-lg">
        <!-- Profile -->
        <div class="flex flex-row sm:p-2">
            <div class="flex flex-row basis-3/4">
                <div>
                    <img src="{{ account.image.url }}"
                   alt="user"
                   width="30"
                   height="15"
                   class="rounded-full w-44 h-44 p-2 sm:w-24 sm:h-24 flex justify-start">
                </div>
                <div class="flex flex-col px-2 py-4 gap-4">
                    <div class="flex flex-row gap-4 items-center">
                        <h2 class="text-4xl font-bold">{{ account.username }}</h2>
                    </div>
                    <div class="flex flex-row gap-10 sm:hidden">
                        <div>
                            <p class="text-slate-500 dark:text-gray-400">
                                Products: <span class="font-bold text-black dark:text-white">{{ products.count }}</span>
                            </p>
                        </div>
                        <div>
                            <p class="text-slate-500 dark:text-gray-400">
                                Followers: <span class="font-bold text-black dark:text-white">{{ account.follows.count }}</span>
                            </p>
                        </div>
                        <div>
                            <p class="text-slate-500 dark:text-gray-400">
                                Following: <span class="font-bold text-black dark:text-white">{{ account_following }}</span>
                            </p>
                        </div>
                    </div>
                    <div class="flex flex-col sm:hidden">
                        <p class="text-slate-500 dark:text-slate-300/60">About:</p>
                        <p class="text-justify">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur obcaecati praesentium necessitatibus, quam, ut commodi eius facilis quisquam voluptatibus sit nam quia laborum laboriosam labore nostrum fugit illum quas. Architecto.
                        </p>
                    </div>
                </div>
            </div>
            <!--mobile-->
            <div class="hidden sm:block">
                
            </div>
            <!-- Buttons -->
            <div class="basis-1/4 flex flex-col items-end gap-2">
                {% if user == account %}
                <a class="w-10 h-10 hover:text-green-hov hover:scale-110 duration-200 transition-all">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-full h-full">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.56.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.893.149c-.425.07-.765.383-.93.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.397.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.273-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.107-1.204l-.527-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894z" />
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                </a>
                {% else %}
                <button x-data="followHandler({% if user in account.follows.all %}true{% else %}false{% endif %},{{ account.follows.count }},{{ account.pk }})" x-html="currentSvg" @click="changeFollow()" class="w-10 h-10 hover:text-green-hov hover:scale-110 duration-200 transition-all">
                </button>
                <a class="w-10 h-10 hover:text-green-hov hover:scale-110 duration-200 transition-all">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="2"
                         stroke="currentColor"
                         class="w-full h-full">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 01-.923 1.785A5.969 5.969 0 006 21c1.282 0 2.47-.402 3.445-1.087.81.22 1.668.337 2.555.337z" />
                    </svg>
                </a>
                {% endif %}
            </div>
        </div>
        <!-- tabs changer -->
        <div class="flex justify-start border-b border-slate-900/10 dark:border-slate-300/10">
            <div class="grid grid-cols-2">
                <div class="flex justify-center cursor-pointer hover:bg-[#c6c6c6] dark:hover:bg-[#595959] border-b-4 border-[#6aa93b] dark:border-[#649d39] px-2 transition-all duration-200 ease-in-out">
                    <p>Items</p>
                </div>
                <div class="flex justify-center cursor-pointer hover:bg-[#c6c6c6] dark:hover:bg-[#595959] px-2 transition-all duration-200 ease-in-out">
                    <p>Favourite</p>
                </div>
            </div>
        </div>
        <!-- Owned products -->
        <div class="grid grid-cols-4 sm:grid-cols-1 md:grid-cols-2 gap-5">
            {% for product in products %}
                <div class="h-80 flex flex-col overflow-hidden">
                    <a href="{% url 'products:product' account.slug product.slug %}"
                       class="shadow-md rounded-lg bg-blend-normal h-3/4">
                        <img src="{{ product.main_image.url }}"
                             alt="image"
                             class="w-full h-full object-cover rounded-lg object-center">
                    </a>
                    <div class="flex flex-row justify-between items-center">
                        <a href="{% url 'products:product' account.slug product.slug %}"
                           class="text-lg font-semibold hover:text-green-hov">{{ product.name }}</a>
                        <p class="flex-none">{{ product.price }} zł</p>
                    </div>
                    <div class="flex flex-row justify-between items-center">
                        <p class="text-gray-700 dark:text-gray-400">{{ product.date|naturalday }}</p>
                        <div class="flex justify-center">
                            <div class="flex justify-center"
                                 x-data="starHandler({% if user in product.stars.all %}true{% else %}false{% endif %},{{ product.stars__count }},{{ product.pk }})">
                                <button x-html="currentSvg"
                                        @click="changeStar()"
                                        class="hover:scale-110 transition-all duration-200 w-6 h-6"
                                        {% if not user.is_authenticated or user == product.owner %}disabled{% endif %}>
                                </button>
                                <p x-text="count" class="ml-1 text-gray-400"></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/apiHandler.js' %}"></script>
{% endblock scripts %}