wildcat/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'


urlpatterns = [
    path('login', views.LoginPage.as_view(), name='login'),
    path('register', views.RegisterPage.as_view(), name='register'),
    path('logout', views.LogOutPage.as_view(), name='logout'),
    path('@<slug:slug>', views.AccountPage.as_view(), name='account_page'),
    path('settings', views.AccountSettingsPage.as_view(), name='settings'),
    path('settings/delete-account', views.AccountDelete.as_view(), name='delete_account'),
]

wildcat/api/urls.py
from django.urls import path
from api.views import ProductListView, AddStarApiView, FollowUserApiView, ChangeCommentlikeApiView, ChangeCommentDislikeApiView, DeleteComment, GetNotifications

app_name = 'api'

urlpatterns = [
    path('products', ProductListView.as_view(), name='products_api'),
    path('products/star/<int:pk>', AddStarApiView.as_view(), name='product_star'),
    path('products/comments/like/<int:pk>', ChangeCommentlikeApiView.as_view(), name='like_comment'),
    path('products/comments/dislike/<int:pk>', ChangeCommentDislikeApiView.as_view(), name='dislike_comment'),
    path('products/comments/delete/<int:pk>', DeleteComment.as_view(), name='delete_comment'),
    path('accounts/follow/<int:pk>', FollowUserApiView.as_view(), name='account_follow'),
    path('notifications', GetNotifications.as_view(), name='notifications')
]

wildcat/products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.IndexPage.as_view(), name='index'),
    path('add-product', views.ProductAdditionPage.as_view(), name='product_addition'),
    path('@<slug:user_slug>/<slug:product_slug>', views.ProductPage.as_view(), name='product'),
    path('@<slug:user_slug>/<slug:product_slug>/edit', views.EditProductPage.as_view(), name='edit_product'),
    path('@<slug:user_slug>/<slug:product_slug>/delete', views.DeleteProduct.as_view(), name='delete_product'),
    path('404', views.tera_test, name='404'),    
]

wildcat/templates/authentication/authenticate.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Wildcat | Login page{% endblock %}
{% block navbar %}{% endblock %}
{% block content %}
    <div class="flex items-center justify-center h-screen">
        <div class="w-1/2 sm:w-4/5 md:w-4/5 h-auto bg-con-l dark:bg-con-d rounded-lg">
            <div class="grid grid-cols-2 sm:grid-cols-1 gap-0 h-full">
                <div class="block sm:hidden">
                    <div class="h-[90%] grid grid-rows-6 my-4 border-r border-slate-900/10 dark:border-slate-300/10 visible sm:invisible">
                        <div class="grid row-span-1 ml-3 text-2xl">
                            <a class="flex justify-start" href="{% url 'products:index' %}">
                                <p class="text-green-l dark:text-green-d">WILD</p>
                            CAT</a>
                        </div>
                        <div class="grid row-span-4 place-content-center text-4xl">
                            <h1 class="text-center">Welcome</h1>
                            <img src="{% static 'img/zbik-login-lm.svg' %}"
                                 class="visible dark:hidden">
                            <img src="{% static 'img/zbik-login-dm.svg' %}" class="hidden dark:block">
                        </div>
                        <div class="grid row-span-1 ml-3 mt-auto">
                            <button class="hover:text-green-hov dark:hover:text-green-hov w-5 h-5 transition-all duration-200 ease-in-out focus:outline-none"
                                    id="theme-toggle">
                            </button>
                        </div>
                    </div>
                </div>
                <div class="my-auto mx-3">
                    <div class="grid grid-cols-2 invisible sm:visible">
                        <div class="flex justify-start text-xl mt-3">
                            <a class="flex justify-start" href="{% url 'products:index' %}">
                                <p class="text-green-l dark:text-green-d">WILD</p>
                            CAT</a>
                        </div>
                        <!--change theme button for mobile devices [not necessary] -->
                    </div>
                    <!--form-->
                    <div class="text-center">
                        <h1 class="text-3xl my-4">Sign In</h1>
                        {% if login_form.errors %}
                            {% for error in login_form.non_field_errors %}
                                <p class="text-red-600 mb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="grid gap-3">
                            <div class="grid grid-cols-12 ml-4 sm:ml-8 w-full">
                                <div class="col-span-3 lg:col-span-1 bg-form-l dark:bg-form-d rounded-l-full absolute">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         fill="none"
                                         viewBox="0 0 24 24"
                                         stroke-width="1.5"
                                         stroke="currentColor"
                                         class="w-6 h-6 my-2 mx-1">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                                    </svg>
                                </div>
                                <div class="col-span-11 sm:col-span-9">
                                    {% render_field login_form.username class="w-full pl-9 py-2 bg-form-l dark:bg-form-d autofill:bg-form-l dark:autofill:bg-form-d rounded-full focus:outline-none border-none focus:ring-0" placeholder="Login or E-mail" %}
                                </div>
                            </div>
                            <div class="grid grid-cols-12 gap-0 ml-4 sm:ml-8 w-full">
                                <div class="col-span-3 lg:col-span-1 bg-form-l dark:bg-form-d rounded-l-full absolute">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         fill="none"
                                         viewBox="0 0 24 24"
                                         stroke-width="1.5"
                                         stroke="currentColor"
                                         class="w-6 h-6 my-2 mx-1">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
                                    </svg>
                                </div>
                                <div class="col-span-11 sm:col-span-9">
                                    {% render_field login_form.password class="w-full pl-9 py-2 bg-form-l dark:bg-form-d autofill:bg-form-l dark:autofill:bg-form-d rounded-full focus:outline-none border-none focus:ring-0" placeholder="Password" %}
                                </div>
                            </div>
                            <div class="grid grid-cols-2 mx-6">
                                <div class="flex justify-start sm:text-sm">
                                    {% render_field login_form.remember_me class="my-auto focus:checked:bg-green-l dark:focus:checked:bg-green-l checked:bg-green-l dark:checked:bg-green-d checked:hover:bg-green-hov cursor-pointer focus:checked:ring-0 focus:ring-0 focus:outline-none rounded-sm" %}
                                    <p class="ml-1">Remember me</p>
                                </div>
                                <div class="flex justify-end sm:text-sm">
                                    <a class="text-green-l hover:text-green-hov dark:text-green-d dark:hover:text-green-hov"
                                       href="#">Forgor password?</a>
                                </div>
                            </div>
                            <div class="mx-3 flex justify-center">
                                <button type="submit"
                                        class="w-1/2 lg:w-full py-2 text-white font-medium bg-green-l rounded-full  hover:bg-green-hov focus:ring-3  focus:ring-green-hov dark:bg-green-d dark:hover:bg-green-hov dark:focus:ring-[#3f284f]">
                                    Login
                                </button>
                            </div>
                        </div>
                    </form>
                    <div class="flex justify-center my-5">
                        <p class="mr-2">Need an account?</p>
                        <a class="text-green-l hover:text-green-hov dark:text-green-d dark:hover:text-green-hov"
                           href="{% url 'accounts:register' %}">Sign Up</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}{% endblock %}

wildcat/templates/authentication/register.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Wildcat | Register{% endblock %}
{% block navbar %}{% endblock %}
{% block content %}
    <div class="flex items-center justify-center h-screen">
        <div class="w-1/2 sm:w-4/5 md:w-4/5 h-auto bg-con-l dark:bg-con-d rounded-lg">
            <div class="grid grid-cols-2 sm:grid-cols-1 gap-0 h-full">
                <div class="block sm:hidden">
                    <div class="h-[90%] grid grid-rows-6 my-4 border-r border-slate-900/10 dark:border-slate-300/10 visible sm:invisible">
                        <div class="grid row-span-1 ml-3 text-2xl">
                            <a class="flex justify-start" href="{% url 'products:index' %}">
                                <p class="text-green-l dark:text-green-d">WILD</p>
                            CAT</a>
                        </div>
                        <div class="grid row-span-4 place-content-center text-4xl">
                            <h1 class="text-center">Welcome</h1>
                            <img src="{% static 'img/zbik-login-lm.svg' %}"
                                 class="visible dark:hidden">
                            <img src="{% static 'img/zbik-login-dm.svg' %}" class="hidden dark:block">
                        </div>
                        <div class="grid row-span-1 ml-3 mt-auto">
                            <button class="hover:text-green-hov dark:hover:text-green-hov w-5 h-5 transition-all duration-200 ease-in-out focus:outline-none"
                                    id="theme-toggle">
                            </button>
                        </div>
                    </div>
                </div>
                <div class="my-auto mx-3">
                    <div class="grid grid-cols-2 invisible sm:visible">
                        <div class="flex justify-start text-xl mt-3">
                            <a class="flex justify-start" href="{% url 'products:index' %}">
                                <p class="text-green-l dark:text-green-d">WILD</p>
                            CAT</a>
                        </div>
                        <!--change theme button for mobile devices [not necessary] -->
                    </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="text-center text-3xl my-5">
                            <h1>Register</h1>
                        </div>
                        <div class="text-center">
                            {% if register_form.errors %}
                                {% for error in register_form.non_field_errors %}
                                    <p class="text-red-600 mb-2">{{ error|escape }}</p>
                                {% endfor %}
                                {% for field in register_form %}
                                    {% for error in field.errors %}
                                        <p class="text-red-600 mb-2">{{ error|escape }}</p>
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="grid gap-3">
                            <!-- <div class="grid grid-cols-12 ml-4 sm:ml-8 w-full">
                                <div class="col-span-1 sm:col-span-3 bg-form-l dark:bg-form-d autofill:bg-form-l dark:autofill:bg-form-d rounded-l-full absolute">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 my-2 mx-1">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                                      </svg>                                      
                                </div>
                                <div class="col-span-11 sm:col-span-9">
                                    <input type="text" class="w-full pl-9 py-2 bg-form-l dark:bg-form-d autofill:bg-form-l dark:autofill:bg-form-d rounded-full focus:outline-none border-none" placeholder="Full Name" required>
                                </div>
                            </div> -->
                            <div class="grid grid-cols-12 ml-4 sm:ml-8 w-full">
                                <div class="col-span-1 sm:col-span-3 bg-form-l dark:bg-form-d autofill:bg-form-l dark:autofill:bg-form-d rounded-l-full absolute">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         fill="none"
                                         viewBox="0 0 24 24"
                                         stroke-width="1.5"
                                         stroke="currentColor"
                                         class="w-6 h-6 my-2 mx-1">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
                                    </svg>
                                </div>
                                <div class="col-span-11 sm:col-span-9">
                                    {% render_field register_form.username class+="w-full pl-9 py-2 bg-form-l dark:bg-form-d autofill:!bg-form-l dark:autofill:!bg-form-d rounded-full border-none focus:ring-0" placeholder="Username" required="true" %}
                                </div>
                            </div>
                            <div class="grid grid-cols-12 ml-4 sm:ml-8 w-full">
                                <div class="col-span-1 sm:col-span-3 bg-form-l dark:bg-form-d autofill:bg-form-l dark:autofill:bg-form-d rounded-l-full absolute">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         fill="none"
                                         viewBox="0 0 24 24"
                                         stroke-width="1.5"
                                         stroke="currentColor"
                                         class="w-6 h-6 my-2 mx-1">
                                        <path stroke-linecap="round" d="M16.5 12a4.5 4.5 0 11-9 0 4.5 4.5 0 019 0zm0 0c0 1.657 1.007 3 2.25 3S21 13.657 21 12a9 9 0 10-2.636 6.364M16.5 12V8.25" />
                                    </svg>
                                </div>
                                <div class="col-span-11 sm:col-span-9">
                                    {% render_field register_form.email class+="w-full pl-9 py-2 bg-form-l dark:bg-form-d autofill:!bg-form-l dark:autofill:!bg-form-d rounded-full border-none focus:ring-0" placeholder="E-mail adress" required="true" %}
                                </div>
                            </div>
                            <div class="grid grid-cols-12 gap-0 ml-4 sm:ml-8 w-full">
                                <div class="col-span-1 sm:col-span-3 bg-form-l dark:bg-form-d autofill:bg-form-l dark:autofill:bg-form-d rounded-l-full absolute">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         fill="none"
                                         viewBox="0 0 24 24"
                                         stroke-width="1.5"
                                         stroke="currentColor"
                                         class="w-6 h-6 my-2 ml-2">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 10.5V6.75a4.5 4.5 0 119 0v3.75M3.75 21.75h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H3.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
                                    </svg>
                                </div>
                                <div class="col-span-11 sm:col-span-9">
                                    {% render_field register_form.password1 class+="w-full pl-9 py-2 bg-form-l dark:bg-form-d autofill:bg-form-l dark:autofill:bg-form-d rounded-full border-none focus:ring-0" placeholder="Password" required="true" %}
                                </div>
                            </div>
                            <div class="grid grid-cols-12 gap-0 ml-4 sm:ml-8 w-full">
                                <div class="col-span-1 sm:col-span-3 bg-form-l dark:bg-form-d autofill:bg-form-l dark:autofill:bg-form-d rounded-l-full absolute">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         fill="none"
                                         viewBox="0 0 24 24"
                                         stroke-width="1.5"
                                         stroke="currentColor"
                                         class="w-6 h-6 my-2 mx-1">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
                                    </svg>
                                </div>
                                <div class="col-span-11 sm:col-span-9">
                                    {% render_field register_form.password2 class+="w-full pl-9 py-2 bg-form-l dark:bg-form-d autofill:bg-form-l dark:autofill:bg-form-d rounded-full border-none focus:ring-0" placeholder="Confirm password" required="true" %}
                                </div>
                            </div>
                            <div class="mx-3 flex justify-center">
                                <button type="submit" class="w-1/2 py-2 text-white font-medium bg-green-l rounded-full  hover:bg-green-hov focus:ring-3  focus:ring-green-hov dark:bg-green-d dark:hover:bg-green-hov dark:focus:ring-green-hov">
                                    Create Account
                                </button>
                            </div>
                        </div>
                        <div class="flex justify-center my-5">
                            <p class="mr-2">Arleady have an account?</p>
                            <a class="text-green-l hover:text-green-hov dark:text-green-d dark:hover:text-green-hov"
                               href="{% url 'accounts:login' %}">Sign In</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}{% endblock %}